In [1]:
import pandas as pd 
import numpy as np 
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC 
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix 

In [2]:
data = pd.read_csv("forestfires.csv")
data

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [3]:
pd.set_option('display.max_columns',None)
data 

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...     ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0   

     daymon  daysat  daysun  daythu  daytue  daywed  monthapr  monthaug  \
0         0       0       0       0       0       0         0         0   
1         0       0       0       0       1       0         0         0   
2         0       1       0       0       0       0         0         0   
3         0       0       0       0       0       0         0         0   
4         0       0       1       0       0       0         0         0   
..      ...     ...     ...     ...     ...     ...       ...       ...   
512       0       0       1       0       0       0         0         1   
513       0       0       1       0       0       0         0         1   
514       0       0       1       0       0       0         0         1   
515       0       1       0       0       0       0         0         1   
516       0       0       0       0       1       0         0         0   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
0           0         0         0         0         0         1         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         0         1         0   
4           0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         0   

     monthnov  monthoct  monthsep size_category  
0           0         0         0         small  
1           0         1         0         small  
2           0         1         0         small  
3           0         0         0         small  
4           0         0         0         small  
..        ...       ...       ...           ...  
512         0         0         0         large  
513         0         0         0         large  
514         0         0         0         large  
515         0         0         0         small  
516         1         0         0         small  

[517 rows x 31 columns]

In [4]:
label_encoder=preprocessing.LabelEncoder()

In [5]:
data['size_category']=label_encoder.fit_transform(data['size_category'])
data 

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...     ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0   

     daymon  daysat  daysun  daythu  daytue  daywed  monthapr  monthaug  \
0         0       0       0       0       0       0         0         0   
1         0       0       0       0       1       0         0         0   
2         0       1       0       0       0       0         0         0   
3         0       0       0       0       0       0         0         0   
4         0       0       1       0       0       0         0         0   
..      ...     ...     ...     ...     ...     ...       ...       ...   
512       0       0       1       0       0       0         0         1   
513       0       0       1       0       0       0         0         1   
514       0       0       1       0       0       0         0         1   
515       0       1       0       0       0       0         0         1   
516       0       0       0       0       1       0         0         0   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
0           0         0         0         0         0         1         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         0         1         0   
4           0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         0   

     monthnov  monthoct  monthsep  size_category  
0           0         0         0              1  
1           0         1         0              1  
2           0         1         0              1  
3           0         0         0              1  
4           0         0         0              1  
..        ...       ...       ...            ...  
512         0         0         0              0  
513         0         0         0              0  
514         0         0         0              0  
515         0         0         0              1  
516         1         0         0              1  

[517 rows x 31 columns]

small = 1, large = 0

In [6]:
data1=data.drop(['month','day'],axis=1)
data1 

FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  daymon  \
0    86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1       0   
1    90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0       0   
2    90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0       0   
3    91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1       0   
4    89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0       0   
..    ...    ...    ...   ...   ...  ..   ...   ...    ...     ...     ...   
512  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0       0   
513  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0       0   
514  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0       0   
515  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0       0   
516  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0       0   

     daysat  daysun  daythu  daytue  daywed  monthapr  monthaug  monthdec  \
0         0       0       0       0       0         0         0         0   
1         0       0       0       1       0         0         0         0   
2         1       0       0       0       0         0         0         0   
3         0       0       0       0       0         0         0         0   
4         0       1       0       0       0         0         0         0   
..      ...     ...     ...     ...     ...       ...       ...       ...   
512       0       1       0       0       0         0         1         0   
513       0       1       0       0       0         0         1         0   
514       0       1       0       0       0         0         1         0   
515       1       0       0       0       0         0         1         0   
516       0       0       0       1       0         0         0         0   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  size_category  
0           0         0              1  
1           1         0              1  
2           1         0              1  
3           0         0              1  
4           0         0              1  
..        ...       ...            ...  
512         0         0              0  
513         0         0              0  
514         0         0              0  
515         0         0              1  
516         0         0              1  

[517 rows x 29 columns]

In [7]:
X = data1.iloc[:,0:28]
Y = data1['size_category']


In [8]:
Y 

0      1
1      1
2      1
3      1
4      1
      ..
512    0
513    0
514    0
515    1
516    1
Name: size_category, Length: 517, dtype: int32

In [9]:
X 

FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  daymon  \
0    86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1       0   
1    90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0       0   
2    90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0       0   
3    91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1       0   
4    89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0       0   
..    ...    ...    ...   ...   ...  ..   ...   ...    ...     ...     ...   
512  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0       0   
513  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0       0   
514  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0       0   
515  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0       0   
516  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0       0   

     daysat  daysun  daythu  daytue  daywed  monthapr  monthaug  monthdec  \
0         0       0       0       0       0         0         0         0   
1         0       0       0       1       0         0         0         0   
2         1       0       0       0       0         0         0         0   
3         0       0       0       0       0         0         0         0   
4         0       1       0       0       0         0         0         0   
..      ...     ...     ...     ...     ...       ...       ...       ...   
512       0       1       0       0       0         0         1         0   
513       0       1       0       0       0         0         1         0   
514       0       1       0       0       0         0         1         0   
515       1       0       0       0       0         0         1         0   
516       0       0       0       1       0         0         0         0   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  
0           0         0  
1           1         0  
2           1         0  
3           0         0  
4           0         0  
..        ...       ...  
512         0         0  
513         0         0  
514         0         0  
515         0         0  
516         0         0  

[517 rows x 28 columns]

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3) #30%

In [11]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((361, 28), (361,), (156, 28), (156,))

# Grid Search CV

# RBF

In [12]:
clf = SVC() #SVC Classification
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10) #model
gsv.fit(X_train,Y_train) 

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [13]:
gsv.best_params_ , gsv.best_score_ 

({'C': 15, 'gamma': 0.5, 'kernel': 'rbf'}, 0.7285285285285286)

In [14]:
clf = SVC(C= 15, gamma = 50)
clf.fit(X_train , Y_train)

SVC(C=15, gamma=50)

In [15]:
Y_pred = clf.predict(X_test) 
Y_pred 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [16]:
acc = accuracy_score(Y_test, Y_pred) * 100
print("Accuracy =", acc)

Accuracy = 75.64102564102564


In [17]:
confusion_matrix(Y_test, Y_pred)

array([[  1,  38],
       [  0, 117]], dtype=int64)

# Linear

In [18]:
clf2 = SVC(kernel= "linear") 
clf2.fit(X_train , Y_train) 

SVC(kernel='linear')

In [19]:
Y_pred2 = clf2.predict(X_test)
Y_pred2 

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1])

In [20]:
acc2 = accuracy_score(Y_test, Y_pred2) * 100
print("Accuracy =", acc2) 

Accuracy = 99.35897435897436


In [21]:
confusion_matrix(Y_test, Y_pred2) 

array([[ 39,   0],
       [  1, 116]], dtype=int64)

# Polynomial

In [22]:
clf3 = SVC(kernel= "poly") 
clf3.fit(X_train , Y_train) 

SVC(kernel='poly')

In [23]:
Y_pred3 = clf3.predict(X_test)
Y_pred3 

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [24]:
acc3 = accuracy_score(Y_test, Y_pred3) * 100
print("Accuracy =", acc3)

Accuracy = 78.84615384615384


In [25]:
confusion_matrix(Y_test, Y_pred3) 

array([[  6,  33],
       [  0, 117]], dtype=int64)

# Sigmoid

In [27]:
clf4 = SVC(kernel= "sigmoid") 
clf4.fit(X_train , Y_train) 

SVC(kernel='sigmoid')

In [29]:
Y_pred4 = clf4.predict(X_test)
Y_pred4 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [30]:
acc4 = accuracy_score(Y_test, Y_pred4) * 100
print("Accuracy =", acc4) 

Accuracy = 74.35897435897436


In [31]:
confusion_matrix(Y_test, Y_pred4) 

array([[  0,  39],
       [  1, 116]], dtype=int64)